import Foundation

let old = HealthRecord(id: "legacy-food-1", kind: "food", day: "2026-08-30", title: "dinner", notes: #"{"food":"breadsticks","quantity":3,"unit":"breadsticks","estimated_macros":{"calories_kcal":420,"protein_g":12,"value_type":"published"}}"#)
let migrated = FoodData.normalized(old)
precondition(migrated.title == "Dinner")
precondition(migrated.foodItems?.first?.name == "Breadsticks")
precondition(migrated.foodItems?.first?.portion == "3 Breadsticks")
precondition(migrated.value == 420 && migrated.protein == 12, "Portion total must not be multiplied by quantity again")
precondition(migrated.notes == nil)
precondition(migrated.id == old.id && migrated.day == old.day)
precondition(FoodData.normalized(migrated) == migrated, "Migration must be idempotent")
var manual = migrated; manual.value = nil; manual.nutritionManualTotals = true; manual.nutritionEstimated = false
precondition(FoodData.normalized(manual).value == nil, "Explicitly clearing a manual total must survive normalization")
let unknown = FoodData.normalized(HealthRecord(kind:"food",day:"2026-08-30",title:"lunch",foodItems:[FoodItem(name:"Salad")]))
precondition(unknown.value == nil && unknown.protein == nil, "Unknown nutrition is not zero")
precondition(FoodData.sum([nil,nil]) == nil)
let text = FoodData.normalized(HealthRecord(kind:"food",day:"2026-08-30",title:"lunch",notes:"Homemade soup"))
precondition(FoodData.notes(text) == "Homemade soup", "Human notes must remain intact")
let one = HealthRecord(kind:"food",day:"2026-08-30",title:"Breakfast",foodItems:[FoodItem(name:"Oatmeal")])
let two = HealthRecord(kind:"food",day:"2026-08-29",title:"Breakfast",foodItems:[FoodItem(name:"Bagel")])
precondition(FoodData.signature(one) != FoodData.signature(two), "Different breakfasts must not collapse together")
print("PASS: old JSON migration, readable portions, known macro preservation, no double multiplication, unknown totals, manual overrides, idempotence, distinct recent meals")
