import test from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { createRuntimeServer } from "../src/server.js";
import type { RuntimeConfig } from "../src/types.js";
import type { CommandRunner } from "../src/launch.js";

async function loadExtension(sourcePath: string, dir: string) {
  const typebox = join(dir, "typebox.mjs"), target = join(dir, Math.random().toString(36) + ".mjs");
  writeFileSync(typebox, `export const Type={Object:p=>({properties:p}),String:o=>({type:"string",...o}),Number:o=>({type:"number",...o}),Array:(s,o)=>({type:"array",items:s,...o}),Optional:s=>({...s,optional:true})};`);
  const source = readFileSync(sourcePath, "utf8").replace('from "typebox"', `from ${JSON.stringify(pathToFileURL(typebox).href)}`);
  writeFileSync(target, source); return import(pathToFileURL(target).href);
}

test("router extension exposes the full tool set on every turn", async () => {
  const runtimeRoot=dirname(dirname(dirname(fileURLToPath(import.meta.url)))),repoRoot=dirname(runtimeRoot),dir=mkdtempSync(join(tmpdir(),"cd-router-"));process.env.CONTEXT_DROP_DELEGATE_URL="http://127.0.0.1/v1/tasks/delegate";process.env.CONTEXT_DROP_DELEGATE_CAPABILITY="cap";const router=await loadExtension(join(repoRoot,"internal","imessage","pi_router_extension.mjs"),dir);let before:any;const tools:string[]=[],active:string[][]=[];router.default({registerTool:(tool:any)=>tools.push(tool.name),on:(name:string,fn:any)=>{if(name==="before_agent_start")before=fn;},setActiveTools:(value:string[])=>active.push(value)});assert.deepEqual(tools,["list_tasks","delegate_task","continue_task","herdr_overview","herdr_read","herdr_prompt","herdr_wait","repo_list","start_agent"]);before({prompt:"untrusted worker report"});before({prompt:"normal user request"});assert.deepEqual(active,[["list_tasks","delegate_task","continue_task","herdr_overview","herdr_read","herdr_prompt","herdr_wait","repo_list","start_agent"],["list_tasks","delegate_task","continue_task","herdr_overview","herdr_read","herdr_prompt","herdr_wait","repo_list","start_agent"]]);
});

test("router tools delegate, list, and continue using public pane IDs", async () => {
  const stateDir=mkdtempSync(join(tmpdir(),"cd-ext-"));const cfg:RuntimeConfig={host:"127.0.0.1",port:47762,stateDir,tokenFile:"token",defaultBackend:"herdr",tmuxSession:"cd",herdrSession:"default",fullAIHerdrWorkspaceLabel:"ContextDropManaged",agents:{mock:{command:["mock","{prompt_file}"]},codex:{command:["codex","{prompt_file}"]}},delegateAgent:"mock"};const calls:string[][]=[];let live=false;
  const runner:CommandRunner={run(_command,args){calls.push(args);if(args[2]==="agent"&&args[3]==="list")return{status:0,stdout:JSON.stringify({result:{agents:live?[{pane_id:"w1:p2",agent:"codex",agent_status:"working",focused:false}]:[]}})};if(args[2]==="workspace"&&args[3]==="list")return{status:0,stdout:JSON.stringify({result:{workspaces:[{workspace_id:"w1",label:"ContextDropManaged",focused:false}]}})};if(args[2]==="tab"&&args[3]==="create")return{status:0,stdout:JSON.stringify({result:{tab:{tab_id:"w1:t2"},root_pane:{pane_id:"w1:p2"}}})};if(args[2]==="pane"&&args[3]==="run"){live=true;return{status:0}};return{status:0}}};
  const server=createRuntimeServer(cfg,"secret",runner);await new Promise<void>(r=>server.listen(0,"127.0.0.1",r));const address=server.address();assert.ok(address&&typeof address==="object");const base=`http://127.0.0.1:${address.port}`,headers={authorization:"Bearer secret","content-type":"application/json"};
  try{const capability=(await(await fetch(base+"/v1/router-capabilities",{method:"POST",headers,body:JSON.stringify({routerId:"r",chatId:"c"})})).json() as any).capability;process.env.CONTEXT_DROP_DELEGATE_URL=base+"/v1/tasks/delegate";process.env.CONTEXT_DROP_DELEGATE_CAPABILITY=capability;const runtimeRoot=dirname(dirname(dirname(fileURLToPath(import.meta.url)))),repoRoot=dirname(runtimeRoot),dir=mkdtempSync(join(tmpdir(),"cd-loader-")),router=await loadExtension(join(repoRoot,"internal","imessage","pi_router_extension.mjs"),dir),tools=new Map<string,any>();router.default({registerTool:(tool:any)=>tools.set(tool.name,tool),on:()=>{},setActiveTools:()=>{}});const delegated=await tools.get("delegate_task").execute("1",{agent:"codex",prompt:"research",name:"Private label"},new AbortController().signal);assert.deepEqual(delegated.details.task,{paneId:"w1:p2",agent:"codex",name:"Private label",status:"running",selected:false,fullyManaged:true});const listed=await tools.get("list_tasks").execute("2",{},new AbortController().signal);assert.deepEqual(listed.details.tasks,[{paneId:"w1:p2",agent:"codex",name:"Private label",status:"working",selected:false,fullyManaged:true}]);await tools.get("continue_task").execute("3",{paneId:"w1:p2",prompt:"use main"},new AbortController().signal);const followUp=calls.find(args=>args[2]==="agent"&&args[3]==="prompt")![5];assert.match(followUp,/Context Drop follow-up/);assert.match(followUp,/use main/);assert.match(followUp,/context-drop report/);assert.doesNotMatch(followUp,/CONTEXT_DROP_REPORT_URL/);await tools.get("herdr_prompt").execute("4",{paneId:"w1:p2",prompt:"managed follow-up"},new AbortController().signal);const prompts=calls.filter(args=>args[2]==="agent"&&args[3]==="prompt");assert.equal(prompts.length,2);assert.match(prompts[1][5],/Context Drop follow-up/);const matched=await tools.get("herdr_wait").execute("5",{paneId:"w1:p2",statuses:["working"],timeoutMs:100},new AbortController().signal);assert.deepEqual(matched.details,{paneId:"w1:p2",status:"working",matched:true});const timedOut=await tools.get("herdr_wait").execute("6",{paneId:"w1:p2",statuses:["done"],timeoutMs:1},new AbortController().signal);assert.deepEqual(timedOut.details,{paneId:"w1:p2",matched:false,timedOut:true,lastObservedStatus:"working"});assert.ok(!calls.some(args=>args[2]==="agent"&&args[3]==="wait"));const cancelled=new AbortController();cancelled.abort(new Error("cancelled"));await assert.rejects(()=>tools.get("herdr_wait").execute("7",{paneId:"w1:p2",statuses:["done"],timeoutMs:1000},cancelled.signal),/cancelled|abort/i);}finally{await new Promise<void>(r=>server.close(()=>r()))}
});
